// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa_zIVeBPVkxlXGcFSVc1E1a2GAepTxb0',
    appId: '1:779911026137:web:98ae836d345da193c175c8',
    messagingSenderId: '779911026137',
    projectId: 'sanberbukatokoid',
    authDomain: 'sanberbukatokoid.firebaseapp.com',
    storageBucket: 'sanberbukatokoid.appspot.com',
    measurementId: 'G-9DQD10LE8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOVTDBTFC3uP_sPXKvfpKjA9C2WY6Q0vA',
    appId: '1:779911026137:android:54646d995a59dff1c175c8',
    messagingSenderId: '779911026137',
    projectId: 'sanberbukatokoid',
    storageBucket: 'sanberbukatokoid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-Gexnix5oqYna1O4pVsBlaHP5D2epzo',
    appId: '1:779911026137:ios:e6d4529066d53f4bc175c8',
    messagingSenderId: '779911026137',
    projectId: 'sanberbukatokoid',
    storageBucket: 'sanberbukatokoid.appspot.com',
    iosBundleId: 'com.example.bukatokoid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2-Gexnix5oqYna1O4pVsBlaHP5D2epzo',
    appId: '1:779911026137:ios:f89d36c0324a92b0c175c8',
    messagingSenderId: '779911026137',
    projectId: 'sanberbukatokoid',
    storageBucket: 'sanberbukatokoid.appspot.com',
    iosBundleId: 'com.example.bukatokoid.RunnerTests',
  );
}
